# Generated by Django 3.1.7 on 2021-02-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('nationality', models.CharField(max_length=100)),
                ('mtongue', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=122)),
                ('dob', models.DateField()),
                ('school', models.CharField(max_length=122)),
                ('sad', models.CharField(max_length=122)),
                ('qua', models.CharField(max_length=122)),
                ('father', models.CharField(max_length=122)),
                ('fmail', models.EmailField(max_length=122)),
                ('phn', models.CharField(max_length=122)),
                ('job', models.CharField(max_length=122)),
                ('mother', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('occ', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=100)),
                ('vill', models.CharField(max_length=100)),
                ('postoffice', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
