# Generated by Django 4.1.4 on 2022-12-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='marksheetdoc',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
