# Generated by Django 4.1.4 on 2022-12-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_student_mail_student_aadhaar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mailid',
            new_name='momail',
        ),
    ]
