# Generated by Django 3.1.7 on 2021-02-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210223_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mmail',
            new_name='mailid',
        ),
    ]
