# Generated by Django 3.1.7 on 2021-02-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210223_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mailid',
            new_name='momail',
        ),
    ]
