# Generated by Django 4.1.4 on 2022-12-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_mailid_student_momail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('aid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('rollnumber', models.CharField(max_length=122)),
                ('enroll', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('cname', models.CharField(max_length=122)),
                ('section', models.CharField(max_length=122)),
                ('status', models.CharField(default='Present', max_length=122)),
                ('remark', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
