# Generated by Django 3.1.7 on 2021-02-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210223_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='momail',
            new_name='mailid',
        ),
    ]
