# Generated by Django 3.1.7 on 2021-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('eid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=122)),
                ('subject', models.CharField(max_length=122)),
                ('ses', models.CharField(max_length=122)),
                ('exam_id', models.CharField(max_length=122)),
                ('type', models.CharField(max_length=122)),
            ],
        ),
    ]
